USE ROLE DATA_OBJECT_ADMIN;
USE WAREHOUSE CUST360_LOAD_WH;

CREATE OR REPLACE VIEW CUST360_NORTHBRIDGE_DATABASE.GOLD.V_KPI_SUMMARY AS
SELECT
    COUNT(DISTINCT c.CUSTOMER_ID)                        AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT a.ACCOUNT_ID)                         AS TOTAL_ACCOUNTS,
    SUM(a.CURRENT_BALANCE)                               AS TOTAL_DEPOSIT_BALANCE,
    AVG(a.CURRENT_BALANCE)                               AS AVG_ACCOUNT_BALANCE,
    SUM(a.INTEREST_EARNED_YTD)                           AS TOTAL_INTEREST_EARNED_YTD,
    COUNT(DISTINCT t.TRANSACTION_ID)                     AS TOTAL_TRANSACTIONS,
    SUM(t.AMOUNT)                                        AS TOTAL_TRANSACTION_VOLUME,
    COUNT(DISTINCT l.LOAN_ID)                            AS TOTAL_LOANS,
    SUM(l.LOAN_AMOUNT)                                   AS TOTAL_LOAN_AMOUNT,
    SUM(l.OUTSTANDING_BALANCE)                           AS TOTAL_LOAN_OUTSTANDING,
    AVG(c.CREDIT_SCORE)                                  AS AVG_CREDIT_SCORE,
    SUM(CASE WHEN t.FRAUD_IS_FLAGGED THEN 1 ELSE 0 END) AS FLAGGED_TRANSACTIONS
FROM CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_DIM_CUSTOMER c
LEFT JOIN CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_ACCOUNT_BALANCES a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_LOANS l ON c.CUSTOMER_ID = l.CUSTOMER_ID;

CREATE OR REPLACE VIEW CUST360_NORTHBRIDGE_DATABASE.GOLD.V_SEGMENT_STATS AS
SELECT
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_TIER,
    COUNT(DISTINCT c.CUSTOMER_ID)       AS CUSTOMER_COUNT,
    AVG(c.ANNUAL_INCOME)                AS AVG_ANNUAL_INCOME,
    AVG(c.CREDIT_SCORE)                 AS AVG_CREDIT_SCORE,
    AVG(c.CHURN_RISK_SCORE)             AS AVG_CHURN_RISK,
    AVG(c.LIFETIME_VALUE_SCORE)         AS AVG_LIFETIME_VALUE,
    AVG(c.TOTAL_DEPOSIT_BALANCE)        AS AVG_DEPOSIT_BALANCE,
    AVG(c.TOTAL_LOAN_OUTSTANDING)       AS AVG_LOAN_OUTSTANDING,
    AVG(c.ESTIMATED_NET_WORTH)          AS AVG_NET_WORTH
FROM CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_DIM_CUSTOMER c
GROUP BY c.CUSTOMER_SEGMENT, c.CUSTOMER_TIER;

CREATE OR REPLACE VIEW CUST360_NORTHBRIDGE_DATABASE.GOLD.V_LOAN_PORTFOLIO AS
SELECT
    l.LOAN_TYPE,
    l.LOAN_PURPOSE,
    l.LOAN_STATUS,
    COUNT(DISTINCT l.LOAN_ID)           AS LOAN_COUNT,
    SUM(l.LOAN_AMOUNT)                  AS TOTAL_LOAN_AMOUNT,
    SUM(l.OUTSTANDING_BALANCE)          AS TOTAL_OUTSTANDING,
    AVG(l.INTEREST_RATE)                AS AVG_INTEREST_RATE,
    AVG(l.TERM_MONTHS)                  AS AVG_TERM_MONTHS,
    SUM(l.MISSED_PAYMENTS)              AS TOTAL_MISSED_PAYMENTS,
    AVG(l.EMI_AMOUNT)                   AS AVG_EMI_AMOUNT,
    SUM(l.ORIGINATION_FEE)              AS TOTAL_ORIGINATION_FEES
FROM CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_LOANS l
GROUP BY l.LOAN_TYPE, l.LOAN_PURPOSE, l.LOAN_STATUS;

CREATE OR REPLACE VIEW CUST360_NORTHBRIDGE_DATABASE.GOLD.V_MONTHLY_TXN_TRENDS AS
SELECT
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE)              AS TXN_MONTH,
    t.TRANSACTION_TYPE,
    t.CHANNEL,
    COUNT(DISTINCT t.TRANSACTION_ID)                     AS TXN_COUNT,
    SUM(t.AMOUNT)                                        AS TOTAL_AMOUNT,
    AVG(t.AMOUNT)                                        AS AVG_AMOUNT,
    SUM(CASE WHEN t.IS_INTERNATIONAL THEN 1 ELSE 0 END) AS INTERNATIONAL_COUNT,
    SUM(CASE WHEN t.FRAUD_IS_FLAGGED THEN 1 ELSE 0 END) AS FRAUD_FLAGGED_COUNT
FROM CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_TRANSACTIONS t
GROUP BY DATE_TRUNC('MONTH', t.TRANSACTION_DATE), t.TRANSACTION_TYPE, t.CHANNEL;

CREATE OR REPLACE VIEW CUST360_NORTHBRIDGE_DATABASE.GOLD.V_REGIONAL_PERF AS
SELECT
    b.REGION,
    b.STATE,
    b.BRANCH_NAME,
    b.BRANCH_TYPE,
    COUNT(DISTINCT a.CUSTOMER_ID)       AS CUSTOMER_COUNT,
    COUNT(DISTINCT a.ACCOUNT_ID)        AS ACCOUNT_COUNT,
    SUM(a.CURRENT_BALANCE)              AS TOTAL_DEPOSITS,
    AVG(a.CURRENT_BALANCE)              AS AVG_ACCOUNT_BALANCE,
    SUM(a.INTEREST_EARNED_YTD)          AS TOTAL_INTEREST_YTD,
    COUNT(DISTINCT l.LOAN_ID)           AS LOAN_COUNT,
    SUM(l.OUTSTANDING_BALANCE)          AS TOTAL_LOAN_OUTSTANDING
FROM CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_DIM_BRANCH b
LEFT JOIN CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_ACCOUNT_BALANCES a ON b.BRANCH_ID = a.BRANCH_ID
LEFT JOIN CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_FACT_LOANS l ON b.BRANCH_ID = l.BRANCH_ID
GROUP BY b.REGION, b.STATE, b.BRANCH_NAME, b.BRANCH_TYPE;

CREATE OR REPLACE VIEW CUST360_NORTHBRIDGE_DATABASE.GOLD.V_RISK_DISTRIBUTION AS
SELECT
    c.RISK_RATING,
    c.CUSTOMER_SEGMENT,
    c.KYC_STATUS,
    c.PEP_STATUS,
    c.FATCA_STATUS,
    COUNT(DISTINCT c.CUSTOMER_ID)       AS CUSTOMER_COUNT,
    AVG(c.CREDIT_SCORE)                 AS AVG_CREDIT_SCORE,
    AVG(c.AML_RISK_SCORE)              AS AVG_AML_RISK_SCORE,
    AVG(c.CHURN_RISK_SCORE)            AS AVG_CHURN_RISK,
    AVG(c.ANNUAL_INCOME)               AS AVG_ANNUAL_INCOME,
    AVG(c.TOTAL_LOAN_OUTSTANDING)      AS AVG_LOAN_OUTSTANDING
FROM CUST360_NORTHBRIDGE_DATABASE.GOLD.CUST360_DIM_CUSTOMER c
GROUP BY c.RISK_RATING, c.CUSTOMER_SEGMENT, c.KYC_STATUS, c.PEP_STATUS, c.FATCA_STATUS;
