SELECT
    COUNT(DISTINCT c.CUSTOMER_ID)                        AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT a.ACCOUNT_ID)                         AS TOTAL_ACCOUNTS,
    SUM(a.CURRENT_BALANCE)                               AS TOTAL_DEPOSIT_BALANCE,
    AVG(a.CURRENT_BALANCE)                               AS AVG_ACCOUNT_BALANCE,
    SUM(a.INTEREST_EARNED_YTD)                           AS TOTAL_INTEREST_EARNED_YTD,
    COUNT(DISTINCT t.TRANSACTION_ID)                     AS TOTAL_TRANSACTIONS,
    SUM(t.AMOUNT)                                        AS TOTAL_TRANSACTION_VOLUME,
    COUNT(DISTINCT l.LOAN_ID)                            AS TOTAL_LOANS,
    SUM(l.LOAN_AMOUNT)                                   AS TOTAL_LOAN_AMOUNT,
    SUM(l.OUTSTANDING_BALANCE)                           AS TOTAL_LOAN_OUTSTANDING,
    AVG(c.CREDIT_SCORE)                                  AS AVG_CREDIT_SCORE,
    SUM(CASE WHEN t.FRAUD_IS_FLAGGED THEN 1 ELSE 0 END) AS FLAGGED_TRANSACTIONS
FROM ${database}.GOLD.CUST360_DIM_CUSTOMER c
LEFT JOIN ${database}.GOLD.CUST360_FACT_ACCOUNT_BALANCES a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN ${database}.GOLD.CUST360_FACT_TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN ${database}.GOLD.CUST360_FACT_LOANS l ON c.CUSTOMER_ID = l.CUSTOMER_ID;