SELECT
    l.LOAN_TYPE,
    l.LOAN_PURPOSE,
    l.LOAN_STATUS,
    COUNT(DISTINCT l.LOAN_ID)           AS LOAN_COUNT,
    SUM(l.LOAN_AMOUNT)                  AS TOTAL_LOAN_AMOUNT,
    SUM(l.OUTSTANDING_BALANCE)          AS TOTAL_OUTSTANDING,
    AVG(l.INTEREST_RATE)                AS AVG_INTEREST_RATE,
    AVG(l.TERM_MONTHS)                  AS AVG_TERM_MONTHS,
    SUM(l.MISSED_PAYMENTS)              AS TOTAL_MISSED_PAYMENTS,
    AVG(l.EMI_AMOUNT)                   AS AVG_EMI_AMOUNT,
    SUM(l.ORIGINATION_FEE)              AS TOTAL_ORIGINATION_FEES
FROM ${database}.GOLD.CUST360_FACT_LOANS l
GROUP BY l.LOAN_TYPE, l.LOAN_PURPOSE, l.LOAN_STATUS;