SELECT
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE)              AS TXN_MONTH,
    t.TRANSACTION_TYPE,
    t.CHANNEL,
    COUNT(DISTINCT t.TRANSACTION_ID)                     AS TXN_COUNT,
    SUM(t.AMOUNT)                                        AS TOTAL_AMOUNT,
    AVG(t.AMOUNT)                                        AS AVG_AMOUNT,
    SUM(CASE WHEN t.IS_INTERNATIONAL THEN 1 ELSE 0 END) AS INTERNATIONAL_COUNT,
    SUM(CASE WHEN t.FRAUD_IS_FLAGGED THEN 1 ELSE 0 END) AS FRAUD_FLAGGED_COUNT
FROM ${database}.GOLD.CUST360_FACT_TRANSACTIONS t
GROUP BY DATE_TRUNC('MONTH', t.TRANSACTION_DATE), t.TRANSACTION_TYPE, t.CHANNEL;