SELECT
    b.REGION,
    b.STATE,
    b.BRANCH_NAME,
    b.BRANCH_TYPE,
    COUNT(DISTINCT a.CUSTOMER_ID)       AS CUSTOMER_COUNT,
    COUNT(DISTINCT a.ACCOUNT_ID)        AS ACCOUNT_COUNT,
    SUM(a.CURRENT_BALANCE)              AS TOTAL_DEPOSITS,
    AVG(a.CURRENT_BALANCE)              AS AVG_ACCOUNT_BALANCE,
    SUM(a.INTEREST_EARNED_YTD)          AS TOTAL_INTEREST_YTD,
    COUNT(DISTINCT l.LOAN_ID)           AS LOAN_COUNT,
    SUM(l.OUTSTANDING_BALANCE)          AS TOTAL_LOAN_OUTSTANDING
FROM ${database}.GOLD.CUST360_DIM_BRANCH b
LEFT JOIN ${database}.GOLD.CUST360_FACT_ACCOUNT_BALANCES a ON b.BRANCH_ID = a.BRANCH_ID
LEFT JOIN ${database}.GOLD.CUST360_FACT_LOANS l ON b.BRANCH_ID = l.BRANCH_ID
GROUP BY b.REGION, b.STATE, b.BRANCH_NAME, b.BRANCH_TYPE;