SELECT
    c.RISK_RATING,
    c.CUSTOMER_SEGMENT,
    c.KYC_STATUS,
    c.PEP_STATUS,
    c.FATCA_STATUS,
    COUNT(DISTINCT c.CUSTOMER_ID)       AS CUSTOMER_COUNT,
    AVG(c.CREDIT_SCORE)                 AS AVG_CREDIT_SCORE,
    AVG(c.AML_RISK_SCORE)              AS AVG_AML_RISK_SCORE,
    AVG(c.CHURN_RISK_SCORE)            AS AVG_CHURN_RISK,
    AVG(c.ANNUAL_INCOME)               AS AVG_ANNUAL_INCOME,
    AVG(c.TOTAL_LOAN_OUTSTANDING)      AS AVG_LOAN_OUTSTANDING
FROM ${database}.GOLD.CUST360_DIM_CUSTOMER c
GROUP BY c.RISK_RATING, c.CUSTOMER_SEGMENT, c.KYC_STATUS, c.PEP_STATUS, c.FATCA_STATUS;