SELECT
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_TIER,
    COUNT(DISTINCT c.CUSTOMER_ID)       AS CUSTOMER_COUNT,
    AVG(c.ANNUAL_INCOME)                AS AVG_ANNUAL_INCOME,
    AVG(c.CREDIT_SCORE)                 AS AVG_CREDIT_SCORE,
    AVG(c.CHURN_RISK_SCORE)             AS AVG_CHURN_RISK,
    AVG(c.LIFETIME_VALUE_SCORE)         AS AVG_LIFETIME_VALUE,
    AVG(c.TOTAL_DEPOSIT_BALANCE)        AS AVG_DEPOSIT_BALANCE,
    AVG(c.TOTAL_LOAN_OUTSTANDING)       AS AVG_LOAN_OUTSTANDING,
    AVG(c.ESTIMATED_NET_WORTH)          AS AVG_NET_WORTH
FROM ${database}.GOLD.CUST360_DIM_CUSTOMER c
GROUP BY c.CUSTOMER_SEGMENT, c.CUSTOMER_TIER;