WITH ranked AS (
    SELECT
        INDEX_RECORD_TS,
        JSON_DATA,
        RECORD_COUNT,
        JSON_VERSION,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        _COPY_DATA_TS,
        ROW_NUMBER() OVER (
            PARTITION BY INDEX_RECORD_TS
            ORDER BY _STG_FILE_LOAD_TS DESC
        ) AS LATEST_FILE_RANK
    FROM ${database}.${source_schema}.${table}
    WHERE INDEX_RECORD_TS IS NOT NULL
)
SELECT
    r.INDEX_RECORD_TS,
    r.JSON_VERSION,
    r._STG_FILE_NAME,
    r._STG_FILE_LOAD_TS,
    r._COPY_DATA_TS,
    r.JSON_DATA:bank::STRING                                        AS BANK_NAME,
    c.value:customer_id::STRING                                     AS CUSTOMER_ID,
    c.value:first_name::STRING                                      AS FIRST_NAME,
    c.value:last_name::STRING                                       AS LAST_NAME,
    c.value:full_name::STRING                                       AS FULL_NAME,
    c.value:email::STRING                                           AS EMAIL,
    c.value:phone_primary::STRING                                   AS PHONE_PRIMARY,
    c.value:phone_secondary::STRING                                 AS PHONE_SECONDARY,
    c.value:date_of_birth::DATE                                     AS DATE_OF_BIRTH,
    c.value:age::INT                                                AS AGE,
    c.value:gender::STRING                                          AS GENDER,
    c.value:marital_status::STRING                                  AS MARITAL_STATUS,
    c.value:nationality::STRING                                     AS NATIONALITY,
    c.value:number_of_dependents::INT                               AS NUMBER_OF_DEPENDENTS,
    c.value:annual_income::FLOAT                                    AS ANNUAL_INCOME,
    c.value:credit_score::INT                                       AS CREDIT_SCORE,
    c.value:credit_score_date::DATE                                 AS CREDIT_SCORE_DATE,
    c.value:customer_segment::STRING                                AS CUSTOMER_SEGMENT,
    c.value:customer_tier::STRING                                   AS CUSTOMER_TIER,
    c.value:risk_rating::STRING                                     AS RISK_RATING,
    c.value:onboarding_channel::STRING                              AS ONBOARDING_CHANNEL,
    c.value:onboarding_date::DATE                                   AS ONBOARDING_DATE,
    c.value:primary_branch::STRING                                  AS PRIMARY_BRANCH,
    c.value:relationship_manager::STRING                            AS RELATIONSHIP_MANAGER,
    c.value:mailing_address_same::BOOLEAN                           AS MAILING_ADDRESS_SAME,
    c.value:address:street::STRING                                  AS ADDRESS_STREET,
    c.value:address:city::STRING                                    AS ADDRESS_CITY,
    c.value:address:state::STRING                                   AS ADDRESS_STATE,
    c.value:address:zip_code::STRING                                AS ADDRESS_ZIP_CODE,
    c.value:address:country::STRING                                 AS ADDRESS_COUNTRY,
    c.value:address:address_type::STRING                            AS ADDRESS_TYPE,
    c.value:address:since_date::DATE                                AS ADDRESS_SINCE_DATE,
    c.value:address:verified::BOOLEAN                               AS ADDRESS_VERIFIED,
    c.value:employment:employer::STRING                             AS EMPLOYER,
    c.value:employment:status::STRING                               AS EMPLOYMENT_STATUS,
    c.value:income_verification:method::STRING                      AS INCOME_VERIFICATION_METHOD,
    c.value:income_verification:verified::BOOLEAN                   AS INCOME_VERIFIED,
    c.value:income_verification:verified_date::DATE                 AS INCOME_VERIFIED_DATE,
    c.value:compliance:kyc_status::STRING                           AS KYC_STATUS,
    c.value:compliance:kyc_completed_date::DATE                     AS KYC_COMPLETED_DATE,
    c.value:compliance:kyc_expiry_date::DATE                        AS KYC_EXPIRY_DATE,
    c.value:compliance:aml_risk_score::FLOAT                        AS AML_RISK_SCORE,
    c.value:compliance:aml_last_reviewed::DATE                      AS AML_LAST_REVIEWED,
    c.value:compliance:pep_status::STRING                           AS PEP_STATUS,
    c.value:compliance:fatca_status::STRING                         AS FATCA_STATUS,
    c.value:compliance:crs_reportable::BOOLEAN                      AS CRS_REPORTABLE,
    c.value:compliance:sanctions_checked::BOOLEAN                   AS SANCTIONS_CHECKED,
    c.value:compliance:sanctions_last_checked::DATE                 AS SANCTIONS_LAST_CHECKED,
    c.value:compliance:tax_residency::STRING                        AS TAX_RESIDENCY,
    c.value:compliance:tin::STRING                                  AS TIN,
    c.value:digital_profile:has_online_banking::BOOLEAN             AS HAS_ONLINE_BANKING,
    c.value:digital_profile:has_mobile_app::BOOLEAN                 AS HAS_MOBILE_APP,
    c.value:digital_profile:mobile_app_version::STRING              AS MOBILE_APP_VERSION,
    c.value:digital_profile:last_login_date::TIMESTAMP_NTZ          AS LAST_LOGIN_DATE,
    c.value:digital_profile:last_login_channel::STRING              AS LAST_LOGIN_CHANNEL,
    c.value:digital_profile:mfa_enabled::BOOLEAN                    AS MFA_ENABLED,
    c.value:digital_profile:mfa_method::STRING                      AS MFA_METHOD,
    c.value:digital_profile:preferred_language::STRING              AS PREFERRED_LANGUAGE,
    c.value:digital_profile:paperless_enrolled::BOOLEAN             AS PAPERLESS_ENROLLED,
    c.value:digital_profile:consent:data_sharing::BOOLEAN           AS CONSENT_DATA_SHARING,
    c.value:digital_profile:consent:marketing_email::BOOLEAN        AS CONSENT_MARKETING_EMAIL,
    c.value:digital_profile:consent:terms_accepted_date::DATE       AS CONSENT_TERMS_ACCEPTED_DATE,
    c.value:digital_profile:consent:terms_version::STRING           AS CONSENT_TERMS_VERSION,
    c.value:digital_profile:notification_preferences:"Email"::BOOLEAN               AS NOTIF_EMAIL,
    c.value:digital_profile:notification_preferences:"SMS"::BOOLEAN                 AS NOTIF_SMS,
    c.value:digital_profile:notification_preferences:"Push Notification"::BOOLEAN   AS NOTIF_PUSH,
    c.value:digital_profile:notification_preferences:"In-App"::BOOLEAN              AS NOTIF_IN_APP,
    c.value:digital_profile:notification_preferences:"Phone"::BOOLEAN               AS NOTIF_PHONE,
    c.value:digital_profile:notification_preferences:"Mail"::BOOLEAN                AS NOTIF_MAIL,
    c.value:financial_summary:total_accounts::INT                   AS TOTAL_ACCOUNTS,
    c.value:financial_summary:total_deposit_balance::FLOAT          AS TOTAL_DEPOSIT_BALANCE,
    c.value:financial_summary:total_loan_outstanding::FLOAT         AS TOTAL_LOAN_OUTSTANDING,
    c.value:financial_summary:total_loans::INT                      AS TOTAL_LOANS,
    c.value:financial_summary:total_credit_cards::INT               AS TOTAL_CREDIT_CARDS,
    c.value:financial_summary:total_credit_card_balance::FLOAT      AS TOTAL_CREDIT_CARD_BALANCE,
    c.value:financial_summary:estimated_net_worth::FLOAT            AS ESTIMATED_NET_WORTH,
    c.value:financial_summary:lifetime_value_score::FLOAT           AS LIFETIME_VALUE_SCORE,
    c.value:financial_summary:churn_risk_score::FLOAT               AS CHURN_RISK_SCORE,
    c.value:financial_summary:relationship_depth::STRING            AS RELATIONSHIP_DEPTH,
    c.value:financial_summary:next_best_product::STRING             AS NEXT_BEST_PRODUCT,
    c.value:metadata:source_system::STRING                          AS SOURCE_SYSTEM,
    c.value:metadata:record_version::INT                            AS RECORD_VERSION,
    c.value:metadata:last_updated::TIMESTAMP_NTZ                    AS METADATA_LAST_UPDATED,
    c.value:metadata:etl_batch_id::STRING                           AS ETL_BATCH_ID,
    c.value:metadata:data_quality_score::FLOAT                      AS DATA_QUALITY_SCORE,
    a.value:account_id::STRING                                      AS ACCOUNT_ID,
    a.value:product_id::STRING                                      AS PRODUCT_ID,
    a.value:product_name::STRING                                    AS PRODUCT_NAME,
    a.value:product_type::STRING                                    AS PRODUCT_TYPE,
    a.value:product_category::STRING                                AS PRODUCT_CATEGORY,
    a.value:account_status::STRING                                  AS ACCOUNT_STATUS,
    a.value:opened_date::DATE                                       AS ACCOUNT_OPENED_DATE,
    a.value:currency::STRING                                        AS ACCOUNT_CURRENCY,
    a.value:current_balance::FLOAT                                  AS CURRENT_BALANCE,
    a.value:available_balance::FLOAT                                AS AVAILABLE_BALANCE,
    a.value:interest_earned_ytd::FLOAT                              AS INTEREST_EARNED_YTD,
    a.value:overdraft_protection::BOOLEAN                           AS OVERDRAFT_PROTECTION,
    a.value:monthly_fee_waived::BOOLEAN                             AS MONTHLY_FEE_WAIVED,
    a.value:last_activity_date::DATE                                AS LAST_ACTIVITY_DATE,
    t.value:transaction_id::STRING                                  AS TRANSACTION_ID,
    t.value:transaction_type::STRING                                AS TRANSACTION_TYPE,
    t.value:transaction_date::DATE                                  AS TRANSACTION_DATE,
    t.value:transaction_timestamp::TIMESTAMP_NTZ                    AS TRANSACTION_TIMESTAMP,
    t.value:amount::FLOAT                                           AS TRANSACTION_AMOUNT,
    t.value:currency::STRING                                        AS TRANSACTION_CURRENCY,
    t.value:description::STRING                                     AS TRANSACTION_DESCRIPTION,
    t.value:status::STRING                                          AS TRANSACTION_STATUS,
    t.value:channel::STRING                                         AS TRANSACTION_CHANNEL,
    t.value:reference_number::STRING                                AS TRANSACTION_REFERENCE,
    t.value:merchant_name::STRING                                   AS MERCHANT_NAME,
    t.value:merchant_category::STRING                               AS MERCHANT_CATEGORY,
    t.value:merchant_city::STRING                                   AS MERCHANT_CITY,
    t.value:is_international::BOOLEAN                               AS IS_INTERNATIONAL,
    t.value:country_code::STRING                                    AS TRANSACTION_COUNTRY_CODE,
    t.value:processing:processor::STRING                            AS PROCESSOR,
    t.value:processing:authorization_code::STRING                   AS AUTHORIZATION_CODE,
    t.value:processing:settlement_date::DATE                        AS SETTLEMENT_DATE,
    t.value:fraud_flags:is_flagged::BOOLEAN                         AS FRAUD_IS_FLAGGED,
    t.value:fraud_flags:flag_reason::STRING                         AS FRAUD_FLAG_REASON,
    t.value:fraud_flags:reviewed::BOOLEAN                           AS FRAUD_REVIEWED,
    l.value:loan_id::STRING                                         AS LOAN_ID,
    l.value:loan_type::STRING                                       AS LOAN_TYPE,
    l.value:loan_purpose::STRING                                    AS LOAN_PURPOSE,
    l.value:loan_status::STRING                                     AS LOAN_STATUS,
    l.value:loan_amount::FLOAT                                      AS LOAN_AMOUNT,
    l.value:outstanding_balance::FLOAT                              AS LOAN_OUTSTANDING_BALANCE,
    l.value:interest_rate::FLOAT                                    AS LOAN_INTEREST_RATE,
    l.value:term_months::INT                                        AS LOAN_TERM_MONTHS,
    l.value:emi_amount::FLOAT                                       AS LOAN_EMI_AMOUNT,
    l.value:disbursement_date::DATE                                 AS LOAN_DISBURSEMENT_DATE,
    l.value:maturity_date::DATE                                     AS LOAN_MATURITY_DATE,
    l.value:payments_made::INT                                      AS LOAN_PAYMENTS_MADE,
    l.value:missed_payments::INT                                    AS LOAN_MISSED_PAYMENTS,
    l.value:next_payment_date::DATE                                 AS LOAN_NEXT_PAYMENT_DATE,
    l.value:next_payment_amount::FLOAT                              AS LOAN_NEXT_PAYMENT_AMOUNT,
    l.value:origination_fee::FLOAT                                  AS LOAN_ORIGINATION_FEE,
    l.value:prepayment_penalty::BOOLEAN                             AS LOAN_PREPAYMENT_PENALTY,
    l.value:collateral::STRING                                      AS LOAN_COLLATERAL,
    l.value:insurance::STRING                                       AS LOAN_INSURANCE,
    l.value:co_borrower::STRING                                     AS LOAN_CO_BORROWER,
    l.value:loan_officer_id::STRING                                 AS LOAN_OFFICER_ID,
    cc.value:card_id::STRING                                        AS CARD_ID,
    cc.value:card_number_masked::STRING                             AS CARD_NUMBER_MASKED,
    cc.value:card_type::STRING                                      AS CARD_TYPE,
    cc.value:status::STRING                                         AS CARD_STATUS,
    cc.value:credit_limit::FLOAT                                    AS CARD_CREDIT_LIMIT,
    cc.value:current_balance::FLOAT                                 AS CARD_CURRENT_BALANCE,
    cc.value:available_credit::FLOAT                                AS CARD_AVAILABLE_CREDIT,
    cc.value:utilization_pct::FLOAT                                 AS CARD_UTILIZATION_PCT,
    cc.value:minimum_payment::FLOAT                                 AS CARD_MINIMUM_PAYMENT,
    cc.value:due_date::DATE                                         AS CARD_DUE_DATE,
    cc.value:issued_date::DATE                                      AS CARD_ISSUED_DATE,
    cc.value:expiry_date::DATE                                      AS CARD_EXPIRY_DATE,
    cc.value:rewards_points::INT                                    AS CARD_REWARDS_POINTS,
    cc.value:rewards_tier::STRING                                   AS CARD_REWARDS_TIER,
    cc.value:contactless_enabled::BOOLEAN                           AS CARD_CONTACTLESS_ENABLED,
    cc.value:international_transactions::BOOLEAN                    AS CARD_INTERNATIONAL_TXN,
    b.value:beneficiary_id::STRING                                  AS BENEFICIARY_ID,
    b.value:name::STRING                                            AS BENEFICIARY_NAME,
    b.value:relationship::STRING                                    AS BENEFICIARY_RELATIONSHIP,
    b.value:percentage::FLOAT                                       AS BENEFICIARY_PERCENTAGE,
    b.value:added_date::DATE                                        AS BENEFICIARY_ADDED_DATE
FROM ranked r,
     LATERAL FLATTEN(input => r.JSON_DATA:customers,  OUTER => TRUE) c,
     LATERAL FLATTEN(input => c.value:accounts,       OUTER => TRUE) a,
     LATERAL FLATTEN(input => c.value:transactions,   OUTER => TRUE) t,
     LATERAL FLATTEN(input => c.value:loans,          OUTER => TRUE) l,
     LATERAL FLATTEN(input => c.value:credit_cards,   OUTER => TRUE) cc,
     LATERAL FLATTEN(input => a.value:beneficiaries,  OUTER => TRUE) b
WHERE r.LATEST_FILE_RANK = 1
