WITH ranked AS (
    SELECT
        INDEX_RECORD_TS,
        JSON_DATA,
        RECORD_COUNT,
        JSON_VERSION,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        _COPY_DATA_TS,
        ROW_NUMBER() OVER (
            PARTITION BY INDEX_RECORD_TS
            ORDER BY _STG_FILE_LOAD_TS DESC
        ) AS LATEST_FILE_RANK
    FROM ${database}.${source_schema}.${table}
    WHERE INDEX_RECORD_TS IS NOT NULL
)
SELECT
    INDEX_RECORD_TS,
    JSON_DATA,
    RECORD_COUNT,
    JSON_VERSION,
    _STG_FILE_NAME,
    _STG_FILE_LOAD_TS,
    _STG_FILE_MD5,
    _COPY_DATA_TS
FROM ranked
WHERE LATEST_FILE_RANK = 1
