WITH flattened AS (
    SELECT
        INDEX_RECORD_TS,
        cust.value:customer_id::TEXT                              AS CUSTOMER_ID,
        cust.value:first_name::TEXT                               AS FIRST_NAME,
        cust.value:last_name::TEXT                                AS LAST_NAME,
        cust.value:full_name::TEXT                                AS FULL_NAME,
        cust.value:email::TEXT                                    AS EMAIL,
        cust.value:phone_primary::TEXT                            AS PHONE_PRIMARY,
        cust.value:phone_secondary::TEXT                          AS PHONE_SECONDARY,
        cust.value:date_of_birth::DATE                            AS DATE_OF_BIRTH,
        cust.value:age::NUMBER                                    AS AGE,
        cust.value:gender::TEXT                                   AS GENDER,
        cust.value:marital_status::TEXT                           AS MARITAL_STATUS,
        cust.value:nationality::TEXT                              AS NATIONALITY,
        cust.value:number_of_dependents::NUMBER                   AS NUMBER_OF_DEPENDENTS,
        cust.value:annual_income::NUMBER(18,2)                    AS ANNUAL_INCOME,
        cust.value:income_verification::TEXT                      AS INCOME_VERIFICATION,
        cust.value:credit_score::NUMBER                           AS CREDIT_SCORE,
        cust.value:credit_score_date::DATE                        AS CREDIT_SCORE_DATE,
        cust.value:customer_segment::TEXT                         AS CUSTOMER_SEGMENT,
        cust.value:customer_tier::TEXT                            AS CUSTOMER_TIER,
        cust.value:risk_rating::TEXT                              AS RISK_RATING,
        cust.value:onboarding_channel::TEXT                       AS ONBOARDING_CHANNEL,
        cust.value:onboarding_date::DATE                          AS ONBOARDING_DATE,
        cust.value:relationship_manager::TEXT                     AS RELATIONSHIP_MANAGER,
        cust.value:mailing_address_same::BOOLEAN                  AS MAILING_ADDRESS_SAME,
        cust.value:address:street::TEXT                           AS ADDRESS_STREET,
        cust.value:address:city::TEXT                             AS ADDRESS_CITY,
        cust.value:address:state::TEXT                            AS ADDRESS_STATE,
        cust.value:address:zip_code::TEXT                         AS ADDRESS_ZIP_CODE,
        cust.value:address:country::TEXT                          AS ADDRESS_COUNTRY,
        cust.value:address:address_type::TEXT                     AS ADDRESS_TYPE,
        cust.value:address:since_date::DATE                       AS ADDRESS_SINCE_DATE,
        cust.value:address:verified::BOOLEAN                      AS ADDRESS_VERIFIED,
        cust.value:employment:employer::TEXT                      AS EMPLOYER,
        cust.value:employment:status::TEXT                        AS EMPLOYMENT_STATUS,
        cust.value:primary_branch:branch_id::TEXT                 AS PRIMARY_BRANCH_ID,
        cust.value:primary_branch:branch_name::TEXT               AS PRIMARY_BRANCH_NAME,
        cust.value:digital_profile:has_mobile_app::BOOLEAN        AS HAS_MOBILE_APP,
        cust.value:digital_profile:has_online_banking::BOOLEAN    AS HAS_ONLINE_BANKING,
        cust.value:digital_profile:last_login_date::DATE          AS LAST_LOGIN_DATE,
        cust.value:digital_profile:last_login_channel::TEXT       AS LAST_LOGIN_CHANNEL,
        cust.value:digital_profile:mfa_enabled::BOOLEAN           AS MFA_ENABLED,
        cust.value:digital_profile:paperless_enrolled::BOOLEAN    AS PAPERLESS_ENROLLED,
        cust.value:compliance:kyc_status::TEXT                    AS KYC_STATUS,
        cust.value:compliance:kyc_completed_date::DATE            AS KYC_COMPLETED_DATE,
        cust.value:compliance:kyc_expiry_date::DATE               AS KYC_EXPIRY_DATE,
        cust.value:compliance:aml_risk_score::NUMBER              AS AML_RISK_SCORE,
        cust.value:compliance:pep_status::TEXT                    AS PEP_STATUS,
        cust.value:compliance:fatca_status::TEXT                  AS FATCA_STATUS,
        cust.value:financial_summary:total_accounts::NUMBER                   AS TOTAL_ACCOUNTS,
        cust.value:financial_summary:total_deposit_balance::NUMBER(18,2)      AS TOTAL_DEPOSIT_BALANCE,
        cust.value:financial_summary:total_loan_outstanding::NUMBER(18,2)     AS TOTAL_LOAN_OUTSTANDING,
        cust.value:financial_summary:total_credit_cards::NUMBER               AS TOTAL_CREDIT_CARDS,
        cust.value:financial_summary:total_credit_card_balance::NUMBER(18,2)  AS TOTAL_CREDIT_CARD_BALANCE,
        cust.value:financial_summary:total_loans::NUMBER                      AS TOTAL_LOANS,
        cust.value:financial_summary:estimated_net_worth::NUMBER(18,2)        AS ESTIMATED_NET_WORTH,
        cust.value:financial_summary:lifetime_value_score::NUMBER             AS LIFETIME_VALUE_SCORE,
        cust.value:financial_summary:churn_risk_score::NUMBER(10,4)           AS CHURN_RISK_SCORE,
        cust.value:financial_summary:relationship_depth::TEXT                 AS RELATIONSHIP_DEPTH,
        cust.value:financial_summary:next_best_product::TEXT                  AS NEXT_BEST_PRODUCT,
        ROW_NUMBER() OVER (PARTITION BY cust.value:customer_id ORDER BY INDEX_RECORD_TS DESC) AS RN
    FROM ${database}.${source_schema}.${table},
         LATERAL FLATTEN(INPUT => JSON_DATA:customers) cust
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    FULL_NAME,
    EMAIL,
    PHONE_PRIMARY,
    PHONE_SECONDARY,
    DATE_OF_BIRTH,
    AGE,
    GENDER,
    MARITAL_STATUS,
    NATIONALITY,
    NUMBER_OF_DEPENDENTS,
    ANNUAL_INCOME,
    INCOME_VERIFICATION,
    CREDIT_SCORE,
    CREDIT_SCORE_DATE,
    CUSTOMER_SEGMENT,
    CUSTOMER_TIER,
    RISK_RATING,
    ONBOARDING_CHANNEL,
    ONBOARDING_DATE,
    RELATIONSHIP_MANAGER,
    MAILING_ADDRESS_SAME,
    ADDRESS_STREET,
    ADDRESS_CITY,
    ADDRESS_STATE,
    ADDRESS_ZIP_CODE,
    ADDRESS_COUNTRY,
    ADDRESS_TYPE,
    ADDRESS_SINCE_DATE,
    ADDRESS_VERIFIED,
    EMPLOYER,
    EMPLOYMENT_STATUS,
    PRIMARY_BRANCH_ID,
    PRIMARY_BRANCH_NAME,
    HAS_MOBILE_APP,
    HAS_ONLINE_BANKING,
    LAST_LOGIN_DATE,
    LAST_LOGIN_CHANNEL,
    MFA_ENABLED,
    PAPERLESS_ENROLLED,
    KYC_STATUS,
    KYC_COMPLETED_DATE,
    KYC_EXPIRY_DATE,
    AML_RISK_SCORE,
    PEP_STATUS,
    FATCA_STATUS,
    TOTAL_ACCOUNTS,
    TOTAL_DEPOSIT_BALANCE,
    TOTAL_LOAN_OUTSTANDING,
    TOTAL_CREDIT_CARDS,
    TOTAL_CREDIT_CARD_BALANCE,
    TOTAL_LOANS,
    ESTIMATED_NET_WORTH,
    LIFETIME_VALUE_SCORE,
    CHURN_RISK_SCORE,
    RELATIONSHIP_DEPTH,
    NEXT_BEST_PRODUCT
FROM flattened
WHERE RN = 1
