SELECT DISTINCT
    PRIMARY_BRANCH_ID               AS BRANCH_ID,
    PRIMARY_BRANCH_NAME             AS BRANCH_NAME,
    PRIMARY_BRANCH_TYPE             AS BRANCH_TYPE,
    PRIMARY_BRANCH_CITY             AS CITY,
    PRIMARY_BRANCH_STATE            AS STATE,
    PRIMARY_BRANCH_REGION           AS REGION,
    PRIMARY_BRANCH_STAFF_COUNT      AS STAFF_COUNT,
    PRIMARY_BRANCH_ESTABLISHED_YEAR AS ESTABLISHED_YEAR
FROM ${database}.${source_schema}.${table}
WHERE PRIMARY_BRANCH_ID IS NOT NULL
