SELECT
    ln.value:loan_id::TEXT                            AS LOAN_ID,
    cust.value:customer_id::TEXT                      AS CUSTOMER_ID,
    cust.value:primary_branch:branch_id::TEXT         AS BRANCH_ID,
    ln.value:loan_type::TEXT                          AS LOAN_TYPE,
    ln.value:loan_purpose::TEXT                       AS LOAN_PURPOSE,
    ln.value:loan_status::TEXT                        AS LOAN_STATUS,
    ln.value:loan_amount::NUMBER(18,2)                AS LOAN_AMOUNT,
    ln.value:outstanding_balance::NUMBER(18,2)        AS OUTSTANDING_BALANCE,
    ln.value:interest_rate::NUMBER(10,4)              AS INTEREST_RATE,
    ln.value:term_months::NUMBER                      AS TERM_MONTHS,
    ln.value:emi_amount::NUMBER(18,2)                 AS EMI_AMOUNT,
    ln.value:disbursement_date::DATE                  AS DISBURSEMENT_DATE,
    ln.value:maturity_date::DATE                      AS MATURITY_DATE,
    ln.value:payments_made::NUMBER                    AS PAYMENTS_MADE,
    ln.value:missed_payments::NUMBER                  AS MISSED_PAYMENTS,
    ln.value:next_payment_date::DATE                  AS NEXT_PAYMENT_DATE,
    ln.value:next_payment_amount::NUMBER(18,2)        AS NEXT_PAYMENT_AMOUNT,
    ln.value:origination_fee::NUMBER(18,2)            AS ORIGINATION_FEE,
    ln.value:prepayment_penalty::BOOLEAN              AS PREPAYMENT_PENALTY,
    ln.value:loan_officer_id::TEXT                    AS LOAN_OFFICER_ID,
    ln.value:collateral:type::TEXT                    AS COLLATERAL_TYPE,
    ln.value:collateral:estimated_value::NUMBER(18,2) AS COLLATERAL_ESTIMATED_VALUE,
    ln.value:collateral:last_appraisal_date::DATE     AS COLLATERAL_LAST_APPRAISAL_DATE,
    ln.value:co_borrower:name::TEXT                   AS CO_BORROWER_NAME,
    ln.value:co_borrower:credit_score::NUMBER         AS CO_BORROWER_CREDIT_SCORE,
    ln.value:co_borrower:annual_income::NUMBER(18,2)  AS CO_BORROWER_ANNUAL_INCOME,
    ln.value:insurance:type::TEXT                     AS INSURANCE_TYPE,
    ln.value:insurance:provider::TEXT                 AS INSURANCE_PROVIDER,
    ln.value:insurance:monthly_premium::NUMBER(18,2)  AS INSURANCE_MONTHLY_PREMIUM
FROM ${database}.${source_schema}.${source_table},
     LATERAL FLATTEN(INPUT => JSON_DATA:customers) cust,
     LATERAL FLATTEN(INPUT => cust.value:loans) ln
