SELECT
    txn.value:transaction_id::TEXT                  AS TRANSACTION_ID,
    cust.value:customer_id::TEXT                    AS CUSTOMER_ID,
    cust.value:primary_branch:branch_id::TEXT       AS BRANCH_ID,
    txn.value:reference_number::TEXT                AS REFERENCE_NUMBER,
    txn.value:transaction_type::TEXT                AS TRANSACTION_TYPE,
    txn.value:transaction_date::DATE                AS TRANSACTION_DATE,
    txn.value:transaction_timestamp::TIMESTAMP_NTZ  AS TRANSACTION_TIMESTAMP,
    txn.value:amount::NUMBER(18,2)                  AS AMOUNT,
    txn.value:currency::TEXT                        AS CURRENCY,
    txn.value:status::TEXT                          AS STATUS,
    txn.value:channel::TEXT                         AS CHANNEL,
    txn.value:description::TEXT                     AS DESCRIPTION,
    txn.value:merchant_name::TEXT                   AS MERCHANT_NAME,
    txn.value:merchant_category::TEXT               AS MERCHANT_CATEGORY,
    txn.value:merchant_city::TEXT                   AS MERCHANT_CITY,
    txn.value:country_code::TEXT                    AS COUNTRY_CODE,
    txn.value:is_international::BOOLEAN             AS IS_INTERNATIONAL,
    txn.value:fraud_flags:is_flagged::BOOLEAN       AS FRAUD_IS_FLAGGED,
    txn.value:fraud_flags:flag_reason::TEXT         AS FRAUD_FLAG_REASON,
    txn.value:fraud_flags:reviewed::BOOLEAN         AS FRAUD_REVIEWED,
    txn.value:processing:authorization_code::TEXT   AS AUTHORIZATION_CODE,
    txn.value:processing:processor::TEXT            AS PROCESSOR,
    txn.value:processing:settlement_date::DATE      AS SETTLEMENT_DATE
FROM ${database}.${source_schema}.${source_table},
     LATERAL FLATTEN(INPUT => JSON_DATA:customers) cust,
     LATERAL FLATTEN(INPUT => cust.value:transactions) txn