SELECT
    ACCOUNT_ID,
    CUSTOMER_ID,
    PRIMARY_BRANCH_ID               AS BRANCH_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_TYPE,
    PRODUCT_CATEGORY,
    ACCOUNT_STATUS,
    ACCOUNT_OPENED_DATE             AS OPENED_DATE,
    ACCOUNT_CURRENCY                AS CURRENCY,
    CURRENT_BALANCE,
    AVAILABLE_BALANCE,
    INTEREST_EARNED_YTD,
    OVERDRAFT_PROTECTION,
    MONTHLY_FEE_WAIVED,
    LAST_ACTIVITY_DATE
FROM ${database}.${source_schema}.${table}
WHERE ACCOUNT_ID IS NOT NULL
